[package]
name = "xcompress"
version = "0.4.4"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/xcompress"
homepage = "https://magiclen.org/xcompress"
keywords = ["compression", "decompression", "zip", "archive", "tar"]
categories = ["command-line-utilities"]
description= "XCompress is a free file archiver utility on Linux, providing multi-format archiving to and extracting from ZIP, Z, GZIP, BZIP2, LZ, XZ, LZMA, 7ZIP, TAR and RAR."
readme = "README.md"
license = "MIT"

[profile.release]
panic = "abort"

[dependencies]
subprocess = "0.1.13"
num_cpus = "1.8.0"
clap = "2.32.0"